# This workflow build Heta platform and share results in "dist" branch

name: Build and Share

on:
  push:
    branches: [ main, '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        node-version: [ 8.x ]
        heta-version: [ latest ]
        platform: [ ubuntu-latest ]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm i -g heta-compiler@${{ matrix.heta-version }}
    - name: Clean and build
      run: |
        rm -rf dist/*
        heta build
    - name: Copy other files to dist
      run: |
        cp -f ./static/README.md ./dist/
    - name: Deploy to "dist" branch only for "main" and "share" pushes
      if: ${{ matrix.node-version == '8.x' && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/share' ) }}
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: dist # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
